os:
  - linux
  - osx
language: generic
sudo: required
dist: bionic
osx_image: xcode11
addons:
  apt:
    update: true
    packages:
      - pkg-config
      - libsdl2-dev
  homebrew:
    update: true
    packages:
      - pkg-config
      - sdl2
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"; fi
script:
  - swift package reset
  - swift build
  - swift test